(define tax 0.065)
(define (reg val subtotal)
	(cond ((< val 0)
	  		(display "Subtotal: $")(display subtotal)(newline)
			(display "Tax: $")(display (* subtotal tax))(newline)
			(display "Total: $")(display (+ subtotal (* subtotal tax)))(newline))
		(else
			(display "Price: $")
			(let ((val (read)))
				(if
					(< val 0)
						(reg val subtotal)
						(reg val (+ subtotal val))
				)
			)
		)
	)
)
